server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
#  servlet:
#    multipart:
#      max-file-size: 50
#      max-request-size: 100MB

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    keyId: LTAI5tQ6i92pNGePAYhY82Xa
    keySecret: bExNrL3katfKdZnJBEXyzyPhjuOuFt
    bucketName: winky-srb-file